services:
  mysql:
    build: ./data/metadata  # Utilise le Dockerfile MySQL dans le dossier database
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mlops_db
      MYSQL_USER: mlops_user
      MYSQL_PASSWORD: mlops_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s
  airflow:
    build: ./airflow
    container_name: airflow_container
    depends_on:
      mysql:
        condition: service_healthy
      minio:
        condition: service_started
      mlflow:
        condition: service_started
    ports:
      - "8085:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags  # Partage les DAGs entre l'hôte et le conteneur
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+pymysql://mlops_user:mlops_pass@mysql_db/mlops_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_CONN_MINIO_CONN=aws://minioadmin:minioadmin@minio:9000?extra__aws__endpoint_url=http%3A%2F%2Fminio:9000
      - AIRFLOW_CONN_MYSQL_CONN_ID=mysql+pymysql://mlops_user:mlops_pass@mysql_db/mlops_db
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    restart: always
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Console web MinIO
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
  mlflow:
    build: ./mlflow
    container_name: mlflow_container
    ports:
      - "5000:5000"
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow_db/mlflow.db
      --default-artifact-root s3://mlops-bucket/mlflow-artifacts/
      --host 0.0.0.0
    volumes:
      - ./mlflow/mlflow_db:/mlflow_db
  fastapi:
    build: ./fastapi  # Path to the directory with your FastAPI Dockerfile and app
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mlflow  # If your API depends on mlflow being available
    environment:
      # Optionally, you can pass MLFLOW and other configuration as environment variables if needed
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
  gradio:
    build: ./gradio  # Directory where your Gradio frontend code and Dockerfile are located
    container_name: gradio
    restart: always
    ports:
      - "7860:7860"
    depends_on:
      - fastapi

volumes:
  mysql_data:
  minio_data:
  mlflow_data: