name: Build & Deploy FastAPI

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest   # or your self-hosted label

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push FastAPI image
        uses: docker/build-push-action@v4
        with:
          context: ./FastAPI
          file: ./FastAPI/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mlops-fastapi:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mlops-fastapi:${{ github.sha }}

      # ─────────── KUBECTL SETUP ───────────
      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig from secret
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Update Deployment image
        run: |
          kubectl set image deployment/fastapi-deployment \
            fastapi=${{ secrets.DOCKERHUB_USERNAME }}/mlops-fastapi:${{ github.sha }} \
            --record

      - name: Wait for rollout to finish
        run: |
          kubectl rollout status deployment/fastapi-deployment --timeout=2m