name: Build, Load & Deploy FastAPI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1) grab your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) bring up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3) install your dependencies and dev‑dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r FastAPI/requirements.txt
          pip install -r tests/requirements-dev.txt

      - name: Start Docker containers
        run: |
          docker-compose up -d
          # wait for everything to be healthy
          echo "🕓 waiting for MLflow to come up…"
          until curl --silent http://localhost:5000/health; do sleep 5; done
          echo "✅ MLflow healthy"
          echo "🕓 waiting for FastAPI…"
          until curl --silent http://localhost:8000/; do sleep 5; done
          echo "✅ FastAPI healthy"

      # 4) run your unit tests
      - name: Run pytest
        run: |
          pytest tests --maxfail=1 --disable-warnings -q

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./FastAPI
          file: ./FastAPI/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mlops-fastapi:latest
