name: Build, Load & Deploy FastAPI (KinD)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & load FastAPI image into KinD
        uses: docker/build-push-action@v4
        with:
          context: ./FastAPI
          file: ./FastAPI/Dockerfile
          load: true
          tags: |
            mlops-fastapi:latest
            mlops-fastapi:${{ github.sha }}

      - name: Set up KinD
        uses: engineerd/setup-kind@v0.6.2
        with:
          name: fastapi-ci
          version: v0.24.0

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to KinD
        run: |
          kubectl apply -f kubernetes/fastapi-deployment.yaml
          kubectl set image deployment/fastapi-deployment \
            fastapi=mlops-fastapi:${{ github.sha }}
          kubectl rollout status deployment/fastapi-deployment --timeout=2m
