name: Build, Push & Deploy FastAPI (KinD)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1) CHECKOUT
    - name: Checkout code
      uses: actions/checkout@v4

    # 2) BUILD & PUSH IMAGE
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & push FastAPI image
      uses: docker/build-push-action@v4
      with:
        context: ./FastAPI
        file: ./FastAPI/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/mlops-fastapi:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/mlops-fastapi:${{ github.sha }}

    # 3) SETUP KIND CLUSTER
    - name: Set up KinD cluster
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.6.0
            
      with:
        version: v0.24.0
        cluster-name: fastapi-ci

    - name: Verify KinD is running
      run: |
        kubectl cluster-info
        kubectl version
        kubectl get pods -n kube-system


    # 4) LOAD IMAGE INTO KIND
    - name: Load FastAPI image into KinD
      run: |
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mlops-fastapi:${{ github.sha }}
        kind load docker-image \
          ${{ secrets.DOCKERHUB_USERNAME }}/mlops-fastapi:${{ github.sha }} \
          --name fastapi-ci

    # 5) DEPLOY TO IN‑CI K8s
    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Apply manifests & roll out
      run: |
        # If first deploy: create namespace / CRDs / etc
        kubectl apply -f kubernetes/fastapi-deployment.yaml
        # Then update image to our exact SHA tag
        kubectl set image deployment/fastapi-deployment \
          fastapi=${{ secrets.DOCKERHUB_USERNAME }}/mlops-fastapi:${{ github.sha }} \
          --record
        kubectl rollout status deployment/fastapi-deployment --timeout=2m
