name: Build, Test & Publish FastAPI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    # we’ll need Docker & Compose to bring up MLflow, MinIO & FastAPI
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Build all service images
        run: |
          # this will rebuild your local ./mlflow and ./minio Dockerfiles too
          docker compose build

      - name: Start services
        run: |
          docker compose up -d minio mlflow fastapi
          # wait for MLflow API
          until curl --silent --fail http://localhost:5000/api/2.0/mlflow/experiments/list; do echo "⏳ waiting for MLflow…"; sleep 5; done
          # wait for FastAPI
          until curl --silent --fail http://localhost:8000/; do echo "⏳ waiting for FastAPI…"; sleep 2; done

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r FastAPI/requirements.txt
          pip install -r tests/requirements-dev.txt

      - name: Run pytest
        run: pytest tests --maxfail=1 --disable-warnings -q

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push FastAPI image
        uses: docker/build-push-action@v2
        with:
          context: ./FastAPI
          file: ./FastAPI/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mlops-fastapi:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mlops-fastapi:${{ github.sha }}
