name: Build, Load & Deploy FastAPI (KinD)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & load FastAPI image into KinD
        uses: docker/build-push-action@v4
        with:
          context: ./FastAPI
          file: ./FastAPI/Dockerfile
          load: true
          tags: |
            mlops-fastapi:latest
            mlops-fastapi:${{ github.sha }}

      - name: Set up KinD
        uses: engineerd/setup-kind@v0.6.2
        with:
          name: fastapi-ci
          version: v0.24.0

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy & Rollout FastAPI
        run: |
          # Apply your manifest (creates or updates)
          kubectl apply -f kubernetes/fastapi-deployment.yaml

          # Either set image or do a restart:
          #kubectl set image deployment/fastapi-deployment \
          #  fastapi=mlops-fastapi:${{ github.sha }} \
          #  --record
          kubectl rollout restart deployment/fastapi-deployment

          # Wait up to 5 minutes for it to become ready
          kubectl rollout status deployment/fastapi-deployment --timeout=5m

      - name: Dump pods on failure
        if: failure()
        run: |
          echo "=== PODS ==="
          kubectl get pods -o wide
          echo "=== DESCRIBE ==="
          kubectl describe pods
          echo "=== LOGS ==="
          for p in $(kubectl get pods -o name); do
            echo "--- logs from $p ---"
            kubectl logs --tail 50 $p || true
          done
